### ISSUE TITLE
Integrate GitHub Actions

### ISSUE THREAD

**Issue by Murderlon** [transloadit/uppy.io#14]
- Linting
- Making sure whenever we do a release in Uppy, this repository updates to the CDN version and is rebuild and deployed.

**Comment by mifi** [comment]
We somehow need to make it so that the `package.json` `version` field gets synced from [uppy](https://github.com/transloadit/uppy)'s version. (Which plugin shall the version be synced with?)  Maybe we either
- manually start a build at https://github.com/transloadit/uppy.io that will pull the latest version from https://github.com/transloadit/uppy
- make it so that a release build in https://github.com/transloadit/uppy will trigger a build here with the released version number as a parameter (is this possible?)

**Comment by Murderlon** [comment]
> * make it so that a release build in https://github.com/transloadit/uppy will trigger a build here with the released version number as a parameter (is this possible?)

This should be possible, yes. Although not with a parameter AFAIK. I think @aduh95 already had some ideas.

**Comment by Murderlon** [comment]
> Which plugin shall the version be synced with?

The same version as the version on the releases page, which is the CDN version.

**Comment by mifi** [comment]
> The same version as the version on the releases page, which is the CDN version. Altough if we don't use versioning in the docs, we may even drop that part and only trigger a build.

which file does that version come from?
we still need the version for the CDN URLs, no?

**Comment by Murderlon** [comment]
> which file does that version come from?

`packages/uppy/package.json`

> we still need the version for the CDN URLs, no?

Ah yes, true!

**Comment by kvz** [comment]
@Murderlon will create a new issue for the remaining steps to update the version number of the CDN bundle into docosaurus
